/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.25
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityLocalFood.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityLocalFood.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "CreateProducerForm_MVC", Title = "CreateProducerForm", SectionName = "CustomWidgets")]
	public class CreateProducerFormController : Controller, IPersonalizable
	{
		// GET: CreateProducerForm
		public ActionResult Index()
		{
			var model = new CreateProducerFormModel();
			return View(model);
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

		public string Message { get; set; }
	}
}