/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.25
</auto-generated>
------------------------------------------------------------------------------ */

using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using System.ComponentModel.DataAnnotations;

namespace SitefinityLocalFood.Mvc.Models
{
	
	public class CreateProducerFormModel
	{
		public string CompanyName { get; set; }

		public string FullName { get; set; }

		public string Image { get; set; }

		public string Phone { get; set; }

		public string Email { get; set; }

		public string Site { get; set; }

		public string Description { get; set; }

		public string Country { get; set; }

		public string City { get; set; }

		public string Zip { get; set; }

		public string Street { get; set; }

		public string UrlAddress { get; set; }
	}
}